### ISSUE TITLE
Error Upon Composer Install

### ISSUE THREAD

**Issue by Alex-Design** [tawfekov/SymfonyVue#1]
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "MinishlinkWebPushBundle" from namespace "Minishlink\Bundle\WebPushBundle".
Did you forget a "use" statement for another namespace?

Looks like an outdated composer.lock file, a composer update fixed it.

**Comment by tawfekov** [comment]
@Alex-Design , Yes indeed,  `composer.lock` file should be removed from git , as a side note `webpush` isn't working 100% on all browsers yet

**Comment by tawfekov** [comment]
I've just deleted that lock file , @Alex-Design, please let me know in case you faced any issue , I'd be happy to help :)
